spring:
  application:
    name: ${APP_NAME}
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
      - id: users-service-login
        uri: lb://users-service
        predicates:
        - Path=/api/v1/users/login
        - Method=POST
        filters:
        - RemoveRequestHeader=Cookie
      - id: users-service
        uri: lb://users-service
        predicates:
        - Path=/api/v1/users/**
        - Method=GET,POST,PUT,DELETE
        - Header=Authorization, Bearer (.*)
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/users-service/(?<segment>.*), /$\{segment}
        - CustomAuthorizationHeaderFilter
server:
  port: ${SERVER_PORT}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true
tw:
  niq:
    token:
      secret: ${TOKEN_SECRET}
      expiration: ${TOKEN_EXPIRATION}