spring:
  application:
    name: ${APP_NAME}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: users-service
        uri: lb://users-service
        predicates:
        - Path=/api/v1/users/**
#        - Path=/users-service/api/v1/users/**
        - Method=GET,POST,PUT,DELETE
        filters:
        - RemoveRequestHeader=Cookie
#        - RewritePath=/users-service/(?<segment>.*), /$\{segment}
server:
  port: ${SERVER_PORT}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true
